# Generated by Django 3.2.4 on 2021-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=2)),
                ('os', models.CharField(max_length=8)),
                ('impressions', models.PositiveSmallIntegerField()),
                ('clicks', models.PositiveSmallIntegerField()),
                ('installs', models.PositiveSmallIntegerField()),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
        ),
    ]
